{% set name = "nvtx" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nvtx-{{ version }}.tar.gz
  sha256: 45c35ea5b0bc229c594ac987910d292ceb87893b13620d9c9bf3fac701acc0ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - nvtx-c
  run:
    - python

test:
  imports:
    - nvtx
    - nvtx._lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/nvtx
  summary: PyNVTX - Python code annotation library
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shwina
